# Generated by Django 4.0.5 on 2022-06-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survived', models.BooleanField(verbose_name='Sobreviveu')),
                ('pclass', models.IntegerField(verbose_name='Classe')),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1, verbose_name='Sexo')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('name', models.TextField(verbose_name='Nome Completo')),
                ('sibsp', models.IntegerField(verbose_name='Número de parentes a bordo')),
                ('parch', models.IntegerField(verbose_name='Números de pais e filhos a bordo')),
                ('fare', models.FloatField(verbose_name='Valor Passagem')),
                ('embarked', models.CharField(choices=[('C', 'Cherbourg'), ('Q', 'Queenstown'), ('S', 'Southampton')], max_length=1, verbose_name='Embarcou')),
            ],
        ),
    ]
